export const STATUSBAR_BACKGROUND='#03A9F4';
export const BACKGROUND='#FAFAFA';
export const BUTTON_BACKGROUND='#03A9F4';
export const DELETE_BUTTON_BACKGROUND='#ed5e68';

export const CARD_TEXT='#000000';

export const CALENDAR_COLORS_TOMATE = '#d50000';
export const CALENDAR_COLORS_MANDARINE = '#f4511e';
export const CALENDAR_COLORS_BANANE = '#f6bf26';
export const CALENDAR_COLORS_BASILIKUM = '#0b8043';
export const CALENDAR_COLORS_SALBEI = '#33b679';
export const CALENDAR_COLORS_HEIDELBEERE = '#3f51b5';
export const CALENDAR_COLORS_LAVENDEL = '#7986cb';
export const CALENDAR_COLORS_WEINTRAUBE = '#8e24aa';
export const CALENDAR_COLORS_FLAMINGO = '#e67c73';
export const CALENDAR_COLORS_GRAFIT = '#616161';
export const CALENDAR_COLORS_DEFAULT = '#039be5';
